//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_06_07_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class productoption
    {
        public int ProductOptionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> OptionID { get; set; }
    
        public virtual option option { get; set; }
        public virtual product product { get; set; }
    }
}
