//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_06_07_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int DetailsID { get; set; }
        public Nullable<int> DetailsOrderID { get; set; }
        public Nullable<int> DetailsProductID { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
